services:

  web:
    build: .
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s node index.js
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - ./src/dump:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - web
